# Gambas Action File 3.0

{ Actions
  { Action mExportar
    Text = "Exportar como CSV"
    Shortcut = ""
    Picture = "icon:/22/save-as"
  }
  { Action mFiltrar
    Text = "Filtrar por este valor"
    Shortcut = ""
    Picture = "dbc_iconos/stock_autofilter.png"
  }
  { Action mFiltro
    Text = "Filtro Avanzado"
    Shortcut = ""
    Picture = "dbc_iconos/stock_advanced-filter.png"
  }
  { Action mNofiltrar
    Text = "Eliminar Filtro"
    Shortcut = ""
    Picture = "dbc_iconos/stock_delete-autofilter.png"
  }
  { Action mOrdenar
    Text = "Ordenar"
    Shortcut = ""
    Picture = "icon:/22/sort-ascent"
  }
  { Action mVerFiltro
    Text = "Ver Filtros Activos"
    Shortcut = ""
    Picture = "dbc_iconos/verfiltro.png"
  }
}

